In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
data = pd.read_csv('wine.csv')

In [ ]:

data = pd.read_csv('wine.csv')
x = data[['Alcohol','Malic_acid','Ash','Alcalinity_ash','Magnesium','Total_phenols','Flavanoids','Nonflavanoid','Proanthocyanins','Color_intensity','Hue','diluted','Proline']].copy()
y = data[['TypesWine']]


In [ ]:
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_val_score
xtrain , xtest , ytrain , ytest  = train_test_split(x,y,test_size=0.3,random_state=20)
ytest.shape

(54, 1)

In [ ]:
from sklearn import svm
modelSVM = svm.SVC(kernel='poly')
modelSVM.fit(xtrain,ytrain)
y_pred = modelSVM.predict(xtest)
yp = np.array(y_pred).reshape(1,-1)
yp

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 3, 2, 1,
        2, 1, 2, 2, 1, 3, 2, 2, 3, 2, 2, 3, 1, 1, 1, 2, 3, 2, 3, 3, 2, 2,
        2, 2, 1, 2, 2, 2, 1, 2, 2, 2]])

In [ ]:
ytest.shape
xc = np.array(ytest).reshape(1,-1)
xc.shape
xc

array([[2, 3, 1, 2, 2, 2, 3, 2, 2, 3, 1, 3, 2, 2, 1, 2, 2, 1, 1, 3, 3, 1,
        2, 1, 3, 2, 1, 3, 2, 2, 2, 2, 3, 2, 1, 1, 1, 2, 3, 2, 1, 1, 2, 2,
        2, 2, 1, 2, 3, 2, 1, 2, 3, 2]])

In [ ]:
num = 0
for i in range(54):
  if yp[0][i] == xc[0][i]:
    num = num+1
num = num/54.0
num


0.7592592592592593

In [ ]:
from sklearn.neural_network import MLPClassifier
clf = MLPClassifier(hidden_layer_sizes=(150,), random_state=1, max_iter=1, warm_start=True)
for i in range(200):
    clf.fit(x, y)
y_pred = clf.predict(xtest)
y_pred

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change

array([2, 3, 1, 2, 2, 2, 3, 2, 2, 3, 1, 3, 2, 2, 1, 2, 2, 1, 1, 3, 3, 1,
       2, 1, 3, 2, 1, 3, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 3, 2, 2, 2, 2, 2,
       2, 2, 1, 2, 3, 2, 1, 2, 3, 2])

In [ ]:
yp = np.array(y_pred).reshape(1,-1)
yp

In [ ]:
num = 0
for i in range(54):
  if yp[0][i] == xc[0][i]:
    num = num+1
num = num/54.0
num

1.0

In [ ]:
y =np.array(ytest)
y